services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwas
    volumes:
      - db-vol:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - http_proxy=http://proxy.prv.put.poznan.pl:8080
        - https_proxy=http://proxy.prv.put.poznan.pl:8080
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=SNPsniper_database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwas
      - http_proxy=http://proxy.prv.put.poznan.pl:8080
      - https_proxy=http://proxy.prv.put.poznan.pl:8080
    depends_on:
      - db

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - http_proxy=http://proxy.prv.put.poznan.pl:8080
        - https_proxy=http://proxy.prv.put.poznan.pl:8080
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend


volumes:
  db-vol:
