services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI=http://localhost/pma/
    depends_on:
      - db
