openapi: 3.1.0
info:
  title: RNA Analysis API
  version: 1.0.0
  description: API do analizy sekwencji RNA oraz pobierania wyników w formacie SVG.

paths:
  /api/analyze/pair:
    post:
      summary: Zlecenie analizy porównawczej sekwencji wild type i mutant
      description: Umożliwia użytkownikowi zlecenie analizy porównawczej sekwencji wild type i mutant.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wildSequence:
                  type: string
                  description: Sekwencja RNA typu dzikiego.
                mutantSequence:
                  type: string
                  description: Sekwencja RNA z SNP.
                analysis_id:
                  type: string
                  format: uuid
                  description: Unikalny identyfikator analizy.
              required:
                - wildSequence
                - mutantSequence
                - analysis_id
      responses:
        '200':
          description: Zlecenie analizy przyjęte.
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis_id:
                    type: string
                    format: uuid
                    description: Unikalny identyfikator analizy.
        '400':
          description: Błędne dane wejściowe.
        '500':
          description: Błąd serwera podczas zlecania analizy.

  /api/analyze/single:
    post:
      summary: Zlecenie analizy pojedynczej sekwencji
      description: Zlecenie analizy dla pojedynczej sekwencji RNA, analizującej możliwe SNP.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wildSequence:
                  type: string
                  description: Sekwencja RNA do analizy.
              required:
                - wildSequence
      responses:
        '200':
          description: Zlecenie analizy przyjęte.
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis_id:
                    type: string
                    format: uuid
                    description: Unikalny identyfikator analizy.
        '400':
          description: Błędne dane wejściowe.
        '500':
          description: Błąd serwera podczas zlecania analizy.

  /api/results/pair/{analysis_id}:
    get:
      summary: Pobranie wyników analizy porównania dwóch sekwencji
      description: Pobranie wyników analizy dla danego identyfikatora.
      parameters:
        - name: analysis_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unikalny identyfikator analizy.
      responses:
        '200':
          description: Wyniki analizy pobrane.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResults'
        '404':
          description: Wyniki analizy nie znalezione.
        '500':
          description: Błąd serwera.

components:
  schemas:
    AnalysisResults:
      type: object
      properties:
        analysis_id:
          type: string
          format: uuid
          description: Unikalny identyfikator analizy.
        results:
          type: object
          properties:
            RNApdist:
              type: number
              description: Wynik RNApdist.
            RNAdistance:
              type: object
              properties:
                f:
                  type: number
                h:
                  type: number
                w:
                  type: number
                c:
                  type: number
                F:
                  type: number
                H:
                  type: number
                W:
                  type: number
                C:
                  type: number
                P:
                  type: number
            RNAfold:
              type: object
              properties:
                wt-dotbracket:
                  type: string
                mut-dotbracket:
                  type: string
            RNAplot:
              type: object
              properties:
                wt-svg:
                  type: string
                  description: Link do SVG wild type.
                mut-svg:
                  type: string
                  description: Link do SVG mutant.
            HIT_tree:
              type: object
              properties:
                tree:
                  type: string
                  description: Link do drzewa HIT.
            status:
              type: string
              description: Status analizy.
              
  /api/results/single/{analysis_id}:
    get:
      summary: Pobranie wyników analizy wszytskich możliwych mutacji jednej sekwencji
      description: Pobranie wyników analizy dla danego identyfikatora.
      parameters:
        - name: analysis_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unikalny identyfikator analizy.
      responses:
        '200':
          description: Wyniki analizy pobrane.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResults'
        '404':
          description: Wyniki analizy nie znalezione.
        '500':
          description: Błąd serwera.
components:
  schemas:
    AnalysisResults:
      type: object
      properties:
        analysis_id:
          type: string
          format: uuid
          description: Unikalny identyfikator analizy.
        results:
          type: object
          properties:
              SNP_variants:
              type: object
              properties:
                variantsfile:
                  type: string
                  description: Link do pliku z wariantami SNP.
            status:
              type: string
              description: Status analizy.

