#!/bin/bash


CURRENT_DIR=$(pwd)

SCRIPT_DIR=$(dirname "$0")


chmod +x "$SCRIPT_DIR/99-find-differences"
chmod +x "$SCRIPT_DIR/98-find-domains"
chmod -R 775 "$SCRIPT_DIR/98-find-domains"


echo "?----------------------------------"
echo "Aktualna zawartość katalogu $CURRENT_DIR:"
ls -l "$CURRENT_DIR"
echo "-----------------------------------"



function plot {
    echo $1 $2
    

    SEQ1=$(head -n 1 "$CURRENT_DIR/$1")
    SEQ2=$(head -n 1 "$CURRENT_DIR/$2")
    
    #first difference between sequences
    FIRST_DIFF_INDEX=0
    for ((i=0; i<${#SEQ1}; i++)); do
        if [ "${SEQ1:$i:1}" != "${SEQ2:$i:1}" ]; then
            FIRST_DIFF_INDEX=$((i))
            break
        fi
    done
    
    echo "First difference index: $FIRST_DIFF_INDEX"
    
    #longer sequence = coloring a nucleotide
    if [ ${#SEQ1} -gt ${#SEQ2} ]; then
        LONGER_SEQ="$1"
    elif [ ${#SEQ2} -gt ${#SEQ1} ]; then
        LONGER_SEQ="$2"
    else
        LONGER_SEQ="both"
    fi
    

    
        RNAplot --layout 4 --post "$("$SCRIPT_DIR/99-find-differences" "$CURRENT_DIR/$1" "$CURRENT_DIR/$2" | awk 'NR == 1')" < "$CURRENT_DIR/$1"
        

        sed -i \
            -e '/^\/outlinecolor/ c /outlinecolor {0.7 setgray} bind def' \
            -e '/fsize 2 div 0/ c fsize 2 div 0 360 arc gsave stroke grestore fill' \
            rna.eps
        
        if [ "$LONGER_SEQ" == "$1" ] || [ "$LONGER_SEQ" == "both" ]; then
        sed -i \
            -e "/^\/drawbases {/,/forall/ s/dup sequence exch 1 getinterval cshow/dup $FIRST_DIFF_INDEX eq { 0 1 0 setrgbcolor } { seqcolor } ifelse &/" \
            rna.eps
        fi
        #conversion
        epstopdf rna.eps
        pdf2svg rna.pdf "${1%.txt}.svg"
        svgo "${1%.txt}.svg"
        rm rna.eps rna.pdf
    
    
    
        RNAplot --layout 4 --post "$("$SCRIPT_DIR/99-find-differences" "$CURRENT_DIR/$1" "$CURRENT_DIR/$2" | awk 'NR == 2')" < "$CURRENT_DIR/$2"
        
        
        sed -i \
            -e '/^\/outlinecolor/ c /outlinecolor {0.7 setgray} bind def' \
            -e '/fsize 2 div 0/ c fsize 2 div 0 360 arc gsave stroke grestore fill' \
            rna.eps
        if [ "$LONGER_SEQ" == "$2" ] || [ "$LONGER_SEQ" == "both" ]; then
        sed -i \
            -e "/^\/drawbases {/,/forall/ s/dup sequence exch 1 getinterval cshow/dup $FIRST_DIFF_INDEX eq { 0 1 0 setrgbcolor } { seqcolor } ifelse &/" \
            rna.eps
        fi
        #conversion
        epstopdf rna.eps
        pdf2svg rna.pdf "${2%.txt}.svg"
        svgo "${2%.txt}.svg"
        rm rna.eps rna.pdf
    
}


plot wt-dotbracket.txt mut-dotbracket.txt


wt_check=$(awk 'NR==2 {print $1}' wt-dotbracket.txt | grep -q '[^.]' && echo true || echo false)
mut_check=$(awk 'NR==2 {print $1}' mut-dotbracket.txt | grep -q '[^.]' && echo true || echo false)

awk 'NR==2 {print $1}' wt-dotbracket.txt
awk 'NR==2 {print $1}' mut-dotbracket.txt
echo "wt_check: $wt_check"
echo "mut_check: $mut_check"

if [ "$wt_check" = true ] && [ "$mut_check" = true ]; then

"$SCRIPT_DIR/98-find-domains" "wt-dotbracket.txt" "mut-dotbracket.txt"


for wt in wt-dotbracket-*.txt; do
    domain_wt=($(echo "${wt##*/}" | sed -E 's/.+-([0-9]+)-([0-9]+).+/\1 \2/g'))
    min_err=1000000


    for mut in mut-dotbracket-*.txt; do
        domain_mut=($(echo "${mut##*/}" | sed -E 's/.+-([0-9]+)-([0-9]+).+/\1 \2/g'))
        err=$(echo "scale=0; sqrt((${domain_wt[0]}-${domain_mut[0]})^2 + (${domain_wt[1]}-${domain_mut[1]})^2)" | bc -l)
        if [[ ${err} -lt ${min_err} ]]; then
            min_err=${err}
            min_mut=${mut}
        fi
    done


    if ! diff -q "$wt" "$min_mut"; then
        plot "${wt##*/}" "${min_mut##*/}"
    fi
done
fi